In [ ]:

#1. Creating Arrays:
import numpy as np
# 1D
a = np.array([1,2,3])
print(a)

# 2D
b = np.array([[1,2,3], [4, 5, 6]])
print(b)
# Array of zeros
zeros = np.zeros((2,3))
print(zeros)
# Array of ones
ones = np.ones((2,3))
print(ones)
# Array with a range of values
range_array = np.arange(0, 10, 2)
print(range_array)
# Array wih evenly spaced values
#2. Indexing and Slicing:
arr = np.array([[1,2,3], [4,5,6]])
# Accessing elements
print(arr[0, 1])
# Slicing
print(arr[:, 1])
# Fancy indexing
c = np.array([10, 20, 30, 40])
print(c)
# Negative indexing
print(c[-1])  # Output: 40
print(c[[0, 2]])  # Output: [10 30]
#3.Reshaping Array:
print(arr)
reshaped = arr.reshape((3,2))
print(reshaped)
#4. Broadcasting:
v = np.array([1,2,3])
u = np.array([[4],[5],[6]])
print(v, 'next')
print(u)
# Broadcasting addition
print(v + u)




[1 2 3]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
2
[2 5]
[10 20 30 40]
40
[10 30]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3] next
[[4]
 [5]
 [6]]
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [3]:
# 2D
b = np.array([[1,2,3], [4, 5, 6]])
print(b)



[[1 2 3]
 [4 5 6]]


In [4]:
# Array of zeros
zeros = np.zeros((2,3))
print(zeros)


[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Array of ones
ones = np.ones((2,3))
print(ones)
# Array with a range of values
range_array = np.arange(0, 10, 2)
print(range_array)
# Array wih evenly spaced values
#2. Indexing and Slicing:
arr = np.array([[1,2,3], [4,5,6]])
# Accessing elements
print(arr[0, 1])
# Slicing
print(arr[:, 1])
# Fancy indexing
c = np.array([10, 20, 30, 40])
print(c)
# Negative indexing
print(c[-1])  # Output: 40
print(c[[0, 2]])  # Output: [10 30]
3#.Reshaping Array:
print(arr)
reshaped = arr.reshape((3,2))
print(reshaped)
#4. Broadcasting:
v = np.array([1,2,3])
u = np.array([[4],[5],[6]])
print(v, 'next')
print(u)
# Broadcasting addition
print(v + u)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
2
[2 5]
[10 20 30 40]
40
[10 30]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3] next
[[4]
 [5]
 [6]]
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [6]:
# Array with a range of values
range_array = np.arange(0, 10, 2)
print(range_array)

[0 2 4 6 8]


In [7]:
# Array wih evenly spaced values
#2. Indexing and Slicing:
arr = np.array([[1,2,3], [4,5,6]])
# Accessing elements
print(arr[0, 1])

2


In [8]:
# Slicing
print(arr[:, 1])

[2 5]


In [9]:
# Fancy indexing
c = np.array([10, 20, 30, 40])
print(c)

[10 20 30 40]


In [10]:
# Negative indexing
print(c[-1])  # Output: 40
print(c[[0, 2]])  # Output: [10 30]

40
[10 30]


In [11]:
3#.Reshaping Array:
print(arr)
reshaped = arr.reshape((3,2))
print(reshaped)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [12]:
#4. Broadcasting:
v = np.array([1,2,3])
u = np.array([[4],[5],[6]])
print(v, 'next')
print(u)

[1 2 3] next
[[4]
 [5]
 [6]]


In [13]:
# Broadcasting addition
print(v + u)


[[5 6 7]
 [6 7 8]
 [7 8 9]]
